# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170828_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='college_captain',
            field=models.BooleanField(default=False),
        ),
    ]
