# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170828_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch_captain',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='college_captain',
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(default='', max_length=20),
        ),
    ]
