# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddSports',
            fields=[
                ('sports_name', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('sports_type', models.CharField(choices=[('SOLO', 'SOLO'), ('TEAM', 'TEAM'), ('BOTH', 'BOTH')], default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AddTeams',
            fields=[
                ('team_name', models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Information Technology', 'Information Technology'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electricals Engineering', 'Electricals Engineering'), ('Electronics and Instrumentation', 'Electronics and Instrumentation'), ('MBA', 'MBA'), ('MCA', 'MCA')], default='', max_length=100, primary_key=True, serialize=False)),
                ('team_initials', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('EN', 'EN'), ('EI', 'EI'), ('MBA', 'MBA'), ('MCA', 'MCA')], default='', max_length=3)),
            ],
        ),
    ]
