# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saksham2017', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddSports',
            new_name='AddSport',
        ),
    ]
