# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saksham2017', '0002_auto_20170829_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialsApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('sports_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saksham2017.AddSport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
