# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saksham2017', '0004_auto_20170830_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialsapplications',
            name='fullname',
        ),
    ]
