# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saksham2017', '0005_remove_trialsapplications_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialsapplications',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
