# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saksham2017', '0010_auto_20170905_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=100)),
                ('opponent', models.CharField(default='', max_length=100)),
                ('pool', models.CharField(default='', max_length=1)),
                ('match_no', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('starting_date', models.DateField(default=datetime.date.today)),
                ('winner', models.CharField(default='', max_length=100)),
                ('runner_up', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='League', max_length=20)),
                ('played', models.BooleanField(default=False)),
            ],
        ),
    ]
